### PR TITLE
Modified index.html for my startup

### PR DESCRIPTION
**Pull request by cedricchristoph**
This is my contribution to your project! I've modified some text in your index.html. Tell me what you think about it.
Regards,
Cedric

### CODE REVIEW

**Comment by cedricchristoph** [comment]
Hey! I'm glad you find my changes useful. I really like the new GIF but I would shrink it in size a little bit.

**Comment by JesusSosaMorales** [comment]
Ok awaiting your changes to merge.

**Comment by cedricchristoph** [comment]
Commit completed! I have also added a margin to the button as it was sticking to the GIF to much.

**Comment by JesusSosaMorales** [comment]
Thank you! Changes merged.

**Pull request merged**
